<a href="https://colab.research.google.com/github/sarthakkaushik/Helper-Codes/blob/main/End_to_End_Sckit_Learn_Workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Get the data ready 

In [16]:
import pandas as pd
import numpy as np

In [3]:
heart_diseaes=pd.read_csv('https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv')

In [5]:
heart_diseaes.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [7]:
#Create X ( feature Matrix)
X= heart_diseaes.drop('target',axis=1)
y= heart_diseaes['target']

In [13]:
#Choose the right model
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()

#We'll keep the default hyperparameter
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [14]:
#3. Fit the modelto training data

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2)


In [15]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [17]:
#Make prediction
y_label=clf.predition(np.array([0,2,3,4]))

AttributeError: ignored

In [18]:
y_pred=clf.predict(X_test)
y_pred

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [19]:
y_test


83     1
101    1
79     1
253    0
38     1
      ..
199    0
42     1
211    0
25     1
165    0
Name: target, Length: 61, dtype: int64

In [20]:
#Evaluate the model on ypred and y_test
clf.score(X_train,y_train)

1.0

In [21]:
clf.score(X_test,y_test)

0.7704918032786885

In [27]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.79      0.77        29
           1       0.80      0.75      0.77        32

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61



In [25]:
confusion_matrix(y_test,y_pred)

array([[23,  6],
       [ 8, 24]])

In [28]:
accuracy_score(y_test,y_pred)

0.7704918032786885

In [30]:
#.5 Improve Model
# Try differen amount of n_estimators

np.random.seed(42)

for  i in range(10,100,10):
  print(f"Tryin model with {i} estimators..")
  clf=RandomForestClassifier(n_estimators=i)
  clf.fit(X_train,y_train)
  print(f"model accuracy of test set : {clf.score(X_test,y_test)*100:.2f}")
  print(" ")

Tryin model with 10 estimators..
model accuracy of test set : 83.61
 
Tryin model with 20 estimators..
model accuracy of test set : 75.41
 
Tryin model with 30 estimators..
model accuracy of test set : 78.69
 
Tryin model with 40 estimators..
model accuracy of test set : 73.77
 
Tryin model with 50 estimators..
model accuracy of test set : 77.05
 
Tryin model with 60 estimators..
model accuracy of test set : 81.97
 
Tryin model with 70 estimators..
model accuracy of test set : 77.05
 
Tryin model with 80 estimators..
model accuracy of test set : 77.05
 
Tryin model with 90 estimators..
model accuracy of test set : 77.05
 


In [31]:
#6 Save the model and load it
import pickle

pickle.dump( clf, open("Random_forest_model_1.pkl","wb"))

In [33]:
# Load the model
loaded_model=pickle.load(open("Random_forest_model_1.pkl","rb"))
loaded_model.score(X_test,y_test)

0.7704918032786885

1.1 Make sure its all Numerical

In [34]:
car_sales=pd.read_csv('https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv')

In [35]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [38]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [39]:
#Split into X/y

X=car_sales.drop("Price",axis=1)
y=car_sales['Price']

#Split the training and test data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [40]:
#Building Machine Learning Model
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

ValueError: ignored

In [44]:
# Turn Categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature=['Make','Colour','Doors']
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("OneHot",one_hot,
                                categorical_feature)],
                                remainder='passthrough')
tranformed_X= transformer.fit_transform(X)
tranformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [46]:
pd.DataFrame(tranformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [49]:
#Lets fit the model
np.random.seed(42)
X_train,X_test,y_train,y_test= train_test_split(tranformed_X,y,test_size=0.2)
model.fit(X_train,y_train)
model.score (X_test,y_test)

0.3235867221569877

## Handlng Missing Data


In [54]:
car_sales_missing=pd.read_csv('https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv')

In [55]:
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [56]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [58]:
# Create X & Y
X= car_sales_missing.drop(['Price'], axis=1)
y=car_sales_missing['Price']

In [66]:
#Lets try to convert our data to numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature=['Make','Colour','Doors']
one_hot=OneHotEncoder()
tranformers=ColumnTransformer([("one-hot",
                                one_hot,
                                categorical_feature)],
                               remainder='passthrough'
                                )
transformed_X= tranformers.fit_transform(X)
transformed_X





<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [69]:
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

#Option1: Fill Missing Value

In [71]:
# Fill the 'Make' Column
car_sales_missing['Make'].fillna("missing",inplace=True)

#Fill the 'Colour' Column
car_sales_missing['Colour'].fillna('missing',inplace=True)

#Fill the Odometer column
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(), inplace=True)

#Fill the Doors

car_sales_missing['Doors'].fillna(4.0,inplace=True)

In [73]:
#check our dataframe
car_sales_missing.isna().sum()


Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [74]:
# Remove rows with missing Price Vaue
car_sales_missing.dropna(inplace=True)

In [75]:
len(car_sales_missing)

950

In [76]:
# Prepare the data again
X=car_sales_missing.drop('Price',axis=1)
y=car_sales_missing['Price']

#train test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Create the column transformer
categorical_feature=['Make','Colour','Doors']
OneHot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_feature)],
                              remainder='passthrough')
transformed_X=transformer.fit_transform(X)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>