<a href="https://colab.research.google.com/github/sarthakkaushik/Helper-Codes/blob/main/Tf_Datasets_Pipline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
sale_number=[21,22,-108,31,-1,32,34,31]

In [3]:
#Xreating tensorflow dataset from a list
tf_dataset= tf.data.Dataset.from_tensor_slices(sale_number)
print(tf_dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [4]:
#Reading the data from tensorflow dataset

for sales in tf_dataset:
  print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [5]:
for sales in tf_dataset:
  print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [6]:
#OR
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
-108
31
-1
32
34
31


In [9]:
#SUPPOSE I WANT TO SEE ONLY FIRT 3 ELEMENTS

for sales in tf_dataset.take(3):
  print(sales.numpy())

21
22
-108


In [11]:
# If I dont want any -ve number in my dataset then you can use FILTER function to filter the data
tf_dataset=tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)


21
22
31
32
34
31


In [12]:
#Suppose I want to perform some operation ( multip with 72) on each element fot the dataset--> I will use Map function for this
tf_dataset=tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)


1512
1584
2232
2304
2448
2232


In [13]:
# Suppose you want SHUFFLE ypur data 
# Refer this link - https://stackoverflow.com/questions/53514495/what-does-batch-repeat-and-shuffle-do-with-tensorflow-dataset
tf_dataset=tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1512
2232
2304
1584
2232
2448


In [14]:
# BATCHING- Suppsoe you want to batch your data
tf_dataset=tf_dataset.batch(3) # It will bacth the data in 3
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

[1512 2304 2232]
[1584 2448 2232]


In [16]:
# CHaining or combining all operation in single line
tf_dataset= tf.data.Dataset.from_tensor_slices(sale_number)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y: y*72).shuffle(2).batch(3)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)


[1584 1512 2232]
[2448 2304 2232]


# Loading Image datasets 

In [17]:
# Code to mount google drive in case you are loading the data from your google drive
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [19]:
#Changing Working Directory
import os
 
# Function to Get the current
# working directory
def current_path():
    print("Current working directory before")
    print(os.getcwd())
    print()
 
 
# Driver's code
# Printing CWD before


current_path()
 
# Changing the CWD
data_path = '/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset'
os.chdir(data_path)
 
# Printing CWD after
current_path()

Current working directory before
/gdrive/My Drive/Machine Learning Datasets/Animie Dataset

Current working directory before
/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset



In [20]:

# importing required modules
from zipfile import ZipFile
  
# specifying the zip file name
file_name = "archive.zip"
  
# opening the zip file in READ mode
with ZipFile(file_name, 'r') as zip:
    # printing all the contents of the zip file
    # zip.printdir()
  
    # extracting all the files
    print('Extracting all the files now...')
    zip.extractall()
    print('Done!')

Extracting all the files now...
Done!


In [29]:
# Reading the IMAGE PATH using tfdataset
image_ds= tf.data.Dataset.list_files('/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/*/*/*',shuffle='False')

for img in image_ds.take(10):
  print(img.numpy())

b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Late_blight/73901132-ade5-4705-9760-c2adcb396cda___RS_Late.B 7065.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Septoria_leaf_spot/253ddc99-8132-4710-bb89-eb83ab271abc___Matt.S_CG 0698.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Leaf_Mold/fee0f163-ef11-48ce-9eff-5546b8ddae91___Crnl_L.Mold 6861.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Pepper__bell___Bacterial_spot/a3ba123a-0100-4f00-9166-9451474e5a8e___NREC_B.Spot 9229.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Pepper__bell___healthy/d81a234b-5eb3-42e3-b998-a7fb261178be___JR_HL 8007.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Bacterial_spot/58674fc9-434d-4afc-879e-712a24831266___GCREC_Bact.Sp 2991.JPG'
b'/gdrive/MyDrive/Machine Learn

Total Images: 20639


# Splitting the Data in Train & Test

In [87]:
#Image count:-
image_count=len(image_ds)
print("Total Images:",image_count)

Total Images: 20639


In [88]:
#For training lest take 80% of the data
train_size=int(image_count*0.8)
#hence my training dataset ds will be
train_ds=image_ds.take(train_size)

test_ds= image_ds.skip(train_size) # this will skip first 80% of the data

In [89]:
# Now feting the class label for of the image ie Y
# if you see the patter , thre is symettry in the path of the file and hence we exploit that
# eg path1= '/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Late_blight/73901132-ade5-4705-9760-c2adcb396cda___RS_Late.B 7065.JPG'
s= '/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Late_blight/73901132-ade5-4705-9760-c2adcb396cda___RS_Late.B 7065.JPG'
s.split('/')[-2]
# great we can get the class label now
# lets create a function for this
import os
def class_label(image_path):
  #since we will get tensor input hence we will not use simple split function  
  # return image.split('/')[-2]
  return tf.strings.split(image_path,os.path.sep)[-2]

# now ideally we should call this fucntion to extract our label

def process_image(image_path):
  label=class_label(image_path) # this will be y for corresponding x
  img= tf.io.read_file(image_path) # this will actually read your image as tensor ie your x's
  img= tf.image.decode_jpeg(img) # Since our file is in jpeg we need tof first decode it
  img= tf.image.resize(img,[128,128]) # We resize the incoming image

  return img, label # we are returing x and its corresponding y


In [90]:
for train in train_ds.take(4):
  print(train.numpy())

  # So this is also file path. Cool!
# now we can call the class_label fucntion that we creaeted on traind_ds to get its corresponding y label
for img,label in train_ds.take(2).map(process_image):
  print('Image: ', img)
  print('Label: ', label)





b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Bacterial_spot/f968f18e-bc41-40bd-b838-f535be8afb93___GCREC_Bact.Sp 5744.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato__Tomato_mosaic_virus/9c96bbe3-5599-4e31-996f-ae37d75872f5___PSU_CG 2215.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Bacterial_spot/076ef17d-dfd3-4dbc-a351-a14eff1aecdb___UF.GRC_BS_Lab Leaf 8980.JPG'
b'/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage/Tomato_Bacterial_spot/6c1529dd-54cb-4e3d-924b-f7f05b6f9a4b___GCREC_Bact.Sp 3269.JPG'
Image:  tf.Tensor(
[[[160.   143.   136.  ]
  [164.25 147.25 140.25]
  [162.25 145.25 138.25]
  ...
  [171.75 154.75 147.75]
  [171.5  154.5  147.5 ]
  [169.5  152.5  145.5 ]]

 [[162.   145.   138.  ]
  [160.25 143.25 136.25]
  [161.25 144.25 137.25]
  ...
  [164.   147.   140.  ]
  [184.25 167.25 160.25]
  [178.75 161.75 154.75]]

 [[15

In [91]:
train_ds= train_ds.map(process_image)
test_ds=test_ds.map(process_image)


In [92]:
train_ds.take(1)

<TakeDataset shapes: ((128, 128, None), ()), types: (tf.float32, tf.string)>

In [93]:
# Now we want to scale of image between 0 and 1

def image_scale(image,label):
  return image/255, label



In [94]:
train_ds= train_ds.map(image_scale)
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())


****Image:  [0.01176471 0.01176471 0.01176471]
****Label:  b'Tomato_Late_blight'
****Image:  [0.66862744 0.5980392  0.5901961 ]
****Label:  b'Tomato_Late_blight'
****Image:  [0.62941176 0.59411764 0.6137255 ]
****Label:  b'Pepper__bell___healthy'
****Image:  [0.56960785 0.5421569  0.56960785]
****Label:  b'Tomato__Tomato_YellowLeaf__Curl_Virus'
****Image:  [0.73333335 0.70980394 0.7176471 ]
****Label:  b'Pepper__bell___Bacterial_spot'


In [97]:
# Using chain rule to do all the proceess in singline of code
final_image_ds= image_ds.map(process_image).map(image_scale)
for image, label in final_image_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.4 0.4 0.4]
****Label:  b'Tomato_Late_blight'
****Image:  [0.51862746 0.4990196  0.5147059 ]
****Label:  b'Tomato_healthy'
****Image:  [0.4598039 0.4245098 0.4362745]
****Label:  b'Potato___Early_blight'
****Image:  [0.41960785 0.4117647  0.43137255]
****Label:  b'Tomato_Early_blight'
****Image:  [0.6872549  0.66764706 0.75784314]
****Label:  b'Pepper__bell___Bacterial_spot'


# NEW / Other way to read and Process data

In [101]:
# data_path = '/gdrive/MyDrive/Machine Learning Datasets/Plant Village-Dataset/PlantVillage'
BATCH_SIZE = 32
IMAGE_SIZE = 256
CHANNELS=3

dataset_df= tf.keras.preprocessing.image_dataset_from_directory(
    'PlantVillage',
    shuffle=True,
    image_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size= BATCH_SIZE
    
)

Found 20638 files belonging to 15 classes.


In [102]:
class_names=dataset_df.class_names
class_names

['Pepper__bell___Bacterial_spot',
 'Pepper__bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Tomato_Bacterial_spot',
 'Tomato_Early_blight',
 'Tomato_Late_blight',
 'Tomato_Leaf_Mold',
 'Tomato_Septoria_leaf_spot',
 'Tomato_Spider_mites_Two_spotted_spider_mite',
 'Tomato__Target_Spot',
 'Tomato__Tomato_YellowLeaf__Curl_Virus',
 'Tomato__Tomato_mosaic_virus',
 'Tomato_healthy']

In [104]:
for img,label in dataset_df.take(1):
  print('Image shape with batch size: ', img.shape) # Here 32 is the size of the batch 
  print('Label: with numeric coding  ', label.numpy())

Image shape with batch size:  (32, 256, 256, 3)
Label: with numeric coding   [ 5  2 12  6  3  8  1  2  7 12 14  5  5  2 12 14  1 12  5 10  6  2 10  3
 10 10 11 12  0 14  8  1]
